#!/usr/bin/python

import os
import sys
import amara
import psycopg2
import psycopg2.extensions

from chat import Chat

def listDir(directory, fileExtList):
	"get list of file info objects for files of particular extensions"
	fileList = [f for f in os.listdir(directory)]
	fileList = [os.path.join(directory, f) for f in fileList
				if os.path.splitext(f)[1].strip('.') in fileExtList and not os.path.isdir(f)]
	return fileList

dsn = "dbname='jmelloy' user='jmelloy'"
connection = psycopg2.connect(dsn)

dir = os.path.join(os.path.expanduser("~"), "Library",
		"Application Support", "Adium 2.0", "Users", "Default", "Logs")

for account in [f for f in os.listdir(dir)
		if os.path.isdir(os.path.join(dir, f))]:
	(service, username) = account.split(".", 1)

	print account

	contact_dir = os.path.join(dir, account)

	for contact in [f for f in os.listdir(contact_dir) if
			os.path.isdir(os.path.join(contact_dir, f))]:

		log_dir = os.path.join(contact_dir, contact)

		logs = listDir(log_dir, ['chatlog', 'adiumLog', 'html'])

		print "\t" + contact + " (" + str(len(logs)) + ")"

		i = 1
		for log in logs:
			#print "\t\t" + os.path.split(log)[1]

			c = Chat(log, username, contact, service, connection)

			if i % 50 == 0:
				print "\t\t" + str(i)

			i += 1

			connection.commit()

connection.close()
